/// Copyright (c) 2019 MemCog Ltd
/// Set GitHub documentation for help
Class Cogs.Lib.Json.Tests.JsonClass.Issue4.MainTestClass Extends Cogs.JsonClass
{

Property MandateListDto As list Of Cogs.Lib.Json.Tests.JsonClass.Issue4.MandateTestClass;

Property PageIndex As %Integer;

Property PageSize As %Integer;

Property ErrorList As list Of %String;

Property ResponseUtcTime As %TimeStamp;

Property UserFriendlyDisplayList As list Of %String;

}

